var app = new Vue({
    el:'#app',
    data:{
        columns:[
            {
                title:'姓名',
                key:'name'
            },
            {
                title:'年龄',
                key:'age',
                sortable:true
            },
            {
                title:'出生日期',
                key:'birthday',
                sortable:true
            },
            {
                title:'地址',
                key:'address'
            }
        ],
        data:[
            {
                name:'王小明',
                age:18,
                birthday:'1992-09-21',
                address:'北京市朝阳区芍药县'
            },
            {
                name:'张小刚',
                age:28,
                birthday:'1982-09-21',
                address:'北京市朝阳阿萨德药县'
            },
            {
                name:'李晓红',
                age:38,
                birthday:'1972-09-21',
                address:'北京市朝阳区格斗术'
            },
            {
                name:'周小伟',
                age:48,
                birthday:'1962-09-21',
                address:'凯撒地方朝阳区芍药县'
            }
        ]
    },
    methods:{
        handleAddData:function () {
            this.data.push({
                name:'刘小天',
                age:19,
                birthday:'1998-09-21',
                address:'凯撒地方朝阳区芍药县'
            },)
        }
    }
})